### ISSUE TITLE
Storybook が動かない問題を修正

### ISSUE THREAD

**Issue by kasaharu** [kasaharu/triangle#445]
```
$ build-storybook
info @storybook/angular v4.1.11
info
info clean outputDir..
info => Copying prebuild dll's..
info => Building manager..
info => Loading manager config..
info => Loading presets
(node:66929) UnhandledPromiseRejectionWarning: Error: Cannot find module 'babel-loader/package.json' from '/Users/wataru.kasahara/work/triangle'
    at module.exports (/Users/wataru.kasahara/work/triangle/node_modules/resolve/lib/sync.js:58:15)
    at isBabelLoader8 (/Users/wataru.kasahara/work/triangle/node_modules/@storybook/core/dist/server/utils/load-custom-babel-config.js:68:52)
    at _default (/Users/wataru.kasahara/work/triangle/node_modules/@storybook/core/dist/server/utils/load-custom-babel-config.js:88:10)
    at Object.babel (/Users/wataru.kasahara/work/triangle/node_modules/@storybook/core/dist/server/common/common-preset.js:19:45)
    at accumulationPromise.then.newConfig (/Users/wataru.kasahara/work/triangle/node_modules/@storybook/core/dist/server/presets.js:78:72)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:66929) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:66929) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 15.65s.
```

babel-loader が入っていないのが原因

**Comment by kasaharu** [comment]
#446 で修正済み
